// M'IAM — Fichier des événements
// Généré automatiquement le 10/08/2026 21:30:26
// Version : 2026.08.10

const EVENEMENTS = [
  {
    "nom": "— MODÈLE À COPIER —",
    "emoji": "📅",
    "association": "",
    "date_debut": "2026-01-01",
    "date_fin": "2026-01-01",
    "heure": "",
    "lat": 0,
    "lng": 0,
    "lieu": "",
    "acces": "",
    "description": "",
    "image": "",
    "site": ""
  },
  {
    "nom": "ECLIPSE DU SOLEIL",
    "emoji": "📅",
    "association": "Johannes KEPLER",
    "date_debut": "2026-08-12",
    "date_fin": "2026-08-12",
    "heure": "19h24 - 21h13",
    "lieu": "Pierre noire (Bigre Mendu)",
    "lat": "47.596900",
    "lng": "-2.851585",
    "acces": "libre, libre, libre",
    "image": "https://i.ibb.co/Z1F9wzfT/eclipse.jpg",
    "site": "",
    "description": "ÉCLIPSE SOLAIRE\nUne éclipse solaire partielle à 96 % aura lieu le 12 août prochain. Le phénomène débutera à 19h24, sera à son maximum à 20h20 et se terminera à 21h13 où elle\ndeviendra difficilement visible.\nPour l’observer, rdv à la Pierre Noire.\n100 paires de lunettes seront offertes et distribuées le mercredi 12 août de 10h à 12h devant la mairie (2 paires max par famille)."
  },
  {
    "nom": "BAL du 15 AOÛT",
    "emoji": "🎉",
    "association": "ACCA Ile-aux-Moines",
    "date_debut": "2026-08-15",
    "date_fin": "2026-08-16",
    "heure": "29h30 - 02h00",
    "lieu": "Place du Marché",
    "lat": "47.596805",
    "lng": "-2.845934",
    "acces": "Accès libre. Venez tous !",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2026/06/AFFICHE-BAL-ACCA-15-08-2026.png.webp",
    "site": "",
    "description": "20h30 Vente des lampions place du marché\n21h00 Bal des enfants place du marché\n22h30 Descente aux lampions au port du Lério\n23h00 Feu d'artifice dans l'anse du Lério\n23h45 Bal poulaire place du marché"
  },
  {
    "nom": "UBU Président",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-09-12",
    "date_fin": "2026-09-12",
    "heure": "18h00 - 19h00",
    "lieu": "Jardin du Rinville",
    "lat": 47.594507,
    "lng": -2.850312,
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/N22kLPnj/prog-herbe-scaled-03.jpg",
    "site": "",
    "description": "Spectacle avancé pour permettre l'observation de l'éclipse du soleil à partir de 19h30."
  },
  {
    "nom": "Anatomie d'un aveuglement",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-09-13",
    "date_fin": "2026-09-13",
    "heure": "19h00 - 21h00",
    "lieu": "Jardin du Rinville",
    "lat": 47.594507,
    "lng": -2.850312,
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/chYCXSJR/prog-herbe-scaled-04.jpg",
    "site": "",
    "description": ""
  },
  {
    "nom": "LA MER NATURE",
    "emoji": "🎨",
    "association": "Sylvie BAC",
    "date_debut": "2026-08-10",
    "date_fin": "2026-08-30",
    "heure": "10h00-18h00",
    "lieu": "La Petite Galerie",
    "lat": 47.6,
    "lng": -2.851,
    "acces": "Accès libre. Venez nombreux.",
    "image": "https://i.ibb.co/wrLmv79w/sylviebac.jpg",
    "site": "https://sylviebacgallery.fr/",
    "description": "Ma démarche :\nJe suis entièrement autodidacte, bien qu’ayant par le passé travaillé avec des artistes professionnels, notamment lorsque je vivais en Espagne, à Zaragoza , ou je travaillais comme peintre en décor , pour la réalisation de façades de bars et restaurants."
  },
  {
    "nom": "exposition Jean-Pierre ARCILE",
    "emoji": "🎨",
    "association": "Jean-Pierre Arcile",
    "date_debut": "2026-08-11",
    "date_fin": "2026-08-15",
    "heure": "10h00 - 12h30 16h00 - 19h00",
    "lat": 47.597088,
    "lng": -2.845835,
    "lieu": "Salle annexe de la Mairie",
    "acces": "Accès libre",
    "description": "Vernissage le mardi 11 août à 11h00",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2026/06/arcile.jpg.webp",
    "site": "www.arcile.fr"
  },
   {
    "nom": "PLEUREUSE DE CENDRES ",
    "emoji": "🎨",
    "association": "LILI CROS",
    "date_debut": "2026-09-16",
    "date_fin": "2026-09-20",
    "heure": "10h00 - 18h00",
    "lat": 47.597088,
    "lng": -2.845835,
    "lieu": "Salle annexe de la Mairie",
    "acces": "Accès libre. Venez nombreux",
    "description": "Lili Cros remonte le temps à la rencontre de la fillette qu’elle a été. Elle expose poèmes, collages et créations sonores\n« Pleureuse de cendres, m’a permis de renouer avec une part oubliée de moi-même »",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2023/04/lili.png.webp",
    "site": "https://lilicros.com/"
  },
  {
    "nom": "CARNET DE VOYAGE",
    "emoji": "🎵",
    "association": "Escales musicales",
    "date_debut": "2026-08-07",
    "date_fin": "2026-08-07",
    "heure": "20h00 - 22h00",
    "lieu": "Église Saint Michel",
    "lat": 47.59857,
    "lng": -2.84267,
    "acces": "Accès avec billet",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2025/10/concert7-aout.jpg.webp",
    "site": "https://www.escalesmusicales.fr/",
    "description": "Amanda Flavier, violon et Elodie Soulard, accordéon"
  },
  {
    "nom": "J'ai mangé ma fourchette",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-08-11",
    "date_fin": "2026-08-11",
    "heure": "19h00 - 21h00",
    "lieu": "Jardin du Rinville",
    "lat": "47.594507",
    "lng": "-2.850312",
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/4wRrPxYK/prog-herbe-scaled-02.jpg",
    "site": "",
    "description": "Un véritable spectacle de music-hall conçu autour de chansons composées par les plus grands spécialistes du genre – Bourvil, Fernandel, les Frères Jacques, Boby Lapointe ou Jean Yanne… "
  }
];
