// M'IAM — Fichier des événements
// Généré automatiquement le 20/07/2026 18:33:45
// Version : 2026.07.20

const EVENEMENTS = [
  {
    "nom": "— MODÈLE À COPIER —",
    "emoji": "📅",
    "association": "",
    "date_debut": "2026-01-01",
    "date_fin": "2026-01-01",
    "heure": "",
    "lieu": "",
    "lat": 0,
    "lng": 0,
    "acces": "",
    "image": "",
    "site": "",
    "description": ""
  },
  {
    "nom": "Bal des pompiers",
    "emoji": "🎪",
    "association": "L'Amicale des Sapeurs Pompiers de l'Ile-aux-Moines",
    "date_debut": "2026-07-25",
    "date_fin": "2026-07-25",
    "heure": "20h00 24h00",
    "lieu": "Place du Marché",
    "lat": 47.5968,
    "lng": -2.8459,
    "acces": "Accès libre - Venez nombreux",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2024/07/BAL-POMPIER-13JUILLET_page-0001.jpg.webp",
    "site": "https://www.mairie-ileauxmoines.fr/agenda/feu-dartifice-et-bal-du-14-juillet/",
    "description": "20h00 : Vente des lampions, Place du marché\n21h00 : Bal des enfants\n23h00 : Feu d'artifice dans la baie du Lério\n23h30 : Bal populaire , Place du marché"
  },
  {
    "nom": "Coeur couleur",
    "emoji": "🎨",
    "association": "Adeline Meilliez",
    "date_debut": "2026-07-22",
    "date_fin": "2026-07-26",
    "heure": "10h00 - 12h00 16h00 - 19h00",
    "lieu": "Salle annexe de la Mairie",
    "lat": 47.597088,
    "lng": -2.845835,
    "acces": "Accès libre",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2026/04/SKM_C451i26032509170-scaled.jpg.webp",
    "site": "https://www.adelinemeilliez.com/",
    "description": "Visual artist"
  },
  {
    "nom": "ACCORDEON et VIOLONCELLE",
    "emoji": "🎵",
    "association": "Moge",
    "date_debut": "2026-07-27",
    "date_fin": "2026-07-27",
    "heure": "17h00 - 18h30",
    "lieu": "Eglise Saint Michel",
    "lat": 47.598626,
    "lng": -2.842659,
    "acces": "Accès libre. Participation aux frais souhaitée",
    "image": "https://ibb.co/Kzpy8hW9",
    "site": "",
    "description": "Eric Blin, accordéon et Yanis Chambrie, violoncelle\nOeuvres de Bach, Borodine, Caccini, Haendel, Vivaldi... "
  },
  {
    "nom": "MARTHE VITRAC",
    "emoji": "🎨",
    "association": "Marthe Vitrac",
    "date_debut": "2026-12-27",
    "date_fin": "2026-12-31",
    "heure": "10h00 - 18h00",
    "lieu": "Salle annexe de la Mairie",
    "lat": 47.597088,
    "lng": -2.845835,
    "acces": "Accès libre",
    "image": "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2026/06/vitrac.jpg.webp",
    "site": "",
    "description": "Fusains, Pastels secs, Crayons de couleurs, Sanguines"
  },
  {
    "nom": "Exposition Respirer l'Instant",
    "emoji": "🎨",
    "association": "Barbara Sabaté Montoriol",
    "date_debut": "2026-07-20",
    "date_fin": "2026-07-26",
    "heure": "10h00 - 13h00 15h00 - 19h00",
    "lieu": "La Petite Galerie",
    "lat": "47.6000",
    "lng": "-2.8510",
    "acces": "Accès libre. Venez nombreux.",
    "image": "https://i.ibb.co/nWfdkNp/expobarbara.jpg",
    "site": "https://fragmentsdesens.com/a-propos-3/",
    "description": "Vernissage le 20 juillet à 18h00\nDedans, dehors, des fleurs et des vues cueillies sur l'Île-aux-Moines entre hiver et printemps 2026."
  },
  {
    "nom": "Bric à Brac de l'APEL",
    "emoji": "🎉",
    "association": "APEL",
    "date_debut": "2026-07-26",
    "date_fin": "2026-07-26",
    "heure": "8h00 - 14h00",
    "lieu": "Place du Marché",
    "lat": "47.5968",
    "lng": "-2.8459",
    "acces": "Accès libre - Venez nombreux",
    "image": "https://i.ibb.co/Q7Dfm0M3/bricabracapel.jpg",
    "site": "",
    "description": "10 € la table. Réservation au 06 14 14 17 70"
  }
];
