// evenements.js — Événements de l'Île-aux-Moines

const EVENEMENTS = [
  {
    nom:         "— MODÈLE À COPIER —",
    emoji:       "📅",
    association: "",
    date_debut:  "2026-01-01",
    date_fin:    "2026-01-01",
    heure:       "",
    lat:         0,
    lng:         0,
    lieu:        "",
    acces:       "",
    description: "",
    image:       "",
    site:        ""
  },
  {
    nom:         "Exposition Etienne Dehau",
    emoji:       "🎨",
    association: "",
    date_debut:  "2026-07-27",
    date_fin:    "2026-08-02",
    heure:       "19h00- 13h00 15h00 - 19h00",
    lat:         47.6,
    lng:         -2.851,
    lieu:        "La Petite Galerie",
    acces:       "Accès libre. Venez nombreux.",
    description: "Entourées par la mer et ouvertes à tous les horizons, les îles offrent un milieu où le ciel, l’eau et la terre se mêlent à l’infini. Les lumières qui les mettent en valeur les façonnent, les transforment et les réinventent en permanence.",
    image:       "https://photos.infolocale.fr/infoLocale/annonce/2026/0722/8942709/_2.jpg",
    site:        "https://etiennedehau.com/"
  },
  {
    nom:         "MARTHE VITRAC",
    emoji:       "🎨",
    association: "Marthe Vitrac",
    date_debut:  "2026-07-27",
    date_fin:    "2026-07-31",
    heure:       "10h00 - 18h00",
    lat:         47.597088,
    lng:         -2.845835,
    lieu:        "Salle annexe de la Mairie",
    acces:       "Accès libre",
    description: "Fusains, Pastels secs, Crayons de couleurs, Sanguines",
    image:       "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2026/06/vitrac.jpg.webp",
    site:        ""
  },
   {
    nom:         "REFLEXIONS NOCTURNES",
    emoji:       "🎨",
    association: "Mathieu Malaud",
    date_debut:  "2026-08-01",
    date_fin:    "2026-08-05",
    heure:       "10h00 - 13h00 16h00 - 19h00",
    lat:         47.597088,
    lng:         -2.845835,
    lieu:        "Salle annexe de la Mairie",
    acces:       "Accès libre",
    description: "'ai choisi la photo, j'ai choisi la nuit, j'ai choisi le littoral breton. Peut-être aurais-je pu opter pour la solution de facilité...",
    image:       "https://www.mairie-ileauxmoines.fr/wp-content/uploads/2023/04/Affiche-Expo-IAM-Matthieu-Malaud.jpg.webp",
    site:        "https://matthieu-malaud.webnode.fr/"
  },
  {
    nom:         "Exposition Domaine du Guerric",
    emoji:       "🎨",
    association: "Domaine du Guerric",
    date_debut:  "2026-07-29",
    date_fin:    "2026-08-05",
    heure:       "10h00 - 12h00 15h00 - 18h00",
    lat:         47.592482,
    lng:         -2.839070,
    lieu:        "Chappelle du Domaine du Guerric",
    acces:       "Accès libre. Venez nombreux",
    description: "Nathalie Jungerman : graveur, Ian Thomson : céramiste, Christophe Grossi: lecture du texte : Les arbres réfléchis, accompagnée de ses\nphotographies projetées",
    image:       "https://i.ibb.co/rfQxM6CQ/8829366916a608c81b93301-14864952-1784712321.jpg",
    site:        ""
  },
  {
    nom:         "L'ESPÈCE EXPLOSIVE",
    emoji:       "🎬",
    association: "Passeurs de Films",
    date_debut:  "2026-07-31",
    date_fin:    "2026-07-31",
    heure:       "21h45 - Oh30",
    lat:         47.592329,
    lng:         -2.839634,
    lieu:        "Parc du château du Guerric",
    acces:       "Entrée libre dans la limite des places disponibles",
    description: "21h45 : Choeur de l'Ile-aux-Moines sous la direction de Lili Cros\n22h15 : Ouverture du festival Passeurs de Films\n22h30 :Avant première de Sarah Arnold.\\nSélection officielle Cannes 2026, Qinzaine des cinéastes.",
    image:       "https://static.wixstatic.com/media/657a55_3841c0acc66d4182832e310649de1fc3~mv2.jpg/v1/fill/w_804,h_1136,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/affiche%20%20passeurs%202026-%20A4%20.jpg",
    site:        "https://www.passeursdefilms.fr"
  },
  {
    "nom": "TRO ENEZ",
    "emoji": "⛵",
    "association": "Comité des fêtes et des régates de l’ile-aux-Moines",
    "date_debut": "2026-08-07",
    "date_fin": "2026-08-07",
    "heure": "",
    "lieu": "Maison située sur la côte ouest, surplombant l’eau entre la Pierre Noire au nord et la pointe du Greignon au sud",
    "lat": "47.595091",
    "lng": "-2.851918",
    "acces": "Ouvert à tous les voiliers. Venez nombreux",
    "image": "https://ibb.co/fGdPPTVN",
    "site": "",
    "description": "Tour de l’île, ouvert à tous les types de bateaux : du dériveur au catamaran, sinagots, quillards, Berny, Guépards….\n(hors planche à voile)\nDépart au canon, pavillon disposé sur une maison située sur la côte ouest, \nsurplombant l’eau entre la Pierre Noire au nord et la pointe du Greignon au sud."
  },
   {
    "nom": "La nostalgie des blattes",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-08-10",
    "date_fin": "2026-08-10",
    "heure": "19h00 - 21h00",
    "lieu": "Jardin du Rinville",
    "lat": "47.594507",
    "lng": "-2.850312",
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/27WBSr85/prog-herbe-scaled-01.jpg",
    "site": "",
    "description": ""
  },
  {
    "nom": "J'ai mangé ma fourchette",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-09-11",
    "date_fin": "2026-09-11",
    "heure": "19h00 - 21h00",
    "lieu": "Jardin du Rinville",
    "lat": "47.455907",
    "lng": "-2.850312",
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/4wRrPxYK/prog-herbe-scaled-02.jpg",
    "site": "",
    "description": ""
  },
  {
    "nom": "UBU Président",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-09-12",
    "date_fin": "2026-09-12",
    "heure": "18h00 - 19h00",
    "lieu": "Jardin du Rinville",
    "lat": "47.594507",
    "lng": "-2.850312",
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/N22kLPnj/prog-herbe-scaled-03.jpg",
    "site": "",
    "description": "Spectacle avancé pour permmettre l'observation de l'éclipse du soleil à partir de 19h30."
  },
  {
    "nom": "Anatomie d'un aveuglement",
    "emoji": "🎭",
    "association": "Théâtre en Herbe",
    "date_debut": "2026-09-13",
    "date_fin": "2026-09-13",
    "heure": "19h00 - 21h00",
    "lieu": "Jardin du Rinville",
    "lat": "47.594507",
    "lng": "-2.850312",
    "acces": "Accès libre. Participation souhaitée.",
    "image": "https://i.ibb.co/chYCXSJR/prog-herbe-scaled-04.jpg",
    "site": "",
    "description": ""
  }
];
